# Generated by Django 5.2.3 on 2026-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_create_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
