from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    ActivateAccountView,
    AdminRoleRequestDetailView,
    AdminRoleRequestListView,
    AdminRoleRequestReviewView,
    GoogleAuthView,
    LoginView,
    LogOutView,
    SignUpView,
    UserRoleRemoveView,
    UserRoleRequestCancelView,
    UserRoleRequestDetailView,
    UserRoleRequestListCreateView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
)

urlpatterns = [
    path(
        "signup/",
        SignUpView.as_view(),
        name="signup",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "login/google/",
        GoogleAuthView.as_view(),
        name="google-login",
    ),
    path(
        "logout/",
        LogOutView.as_view(),
        name="logout",
    ),
    path(
        "token/refresh/",
        TokenRefreshView.as_view(),
        name="token-refresh",
    ),
    path(
        "activate/<uidb64>/<token>/",
        ActivateAccountView.as_view(),
        name="activate-account",
    ),
    path(
        "role-requests/",
        UserRoleRequestListCreateView.as_view(),
        name="role-request-list-create",
    ),
    path(
        "role-requests/<int:pk>/",
        UserRoleRequestDetailView.as_view(),
        name="role-request-detail",
    ),
    path(
        "role-requests/<int:pk>/cancel/",
        UserRoleRequestCancelView.as_view(),
        name="role-request-cancel",
    ),
    path(
        "admin/role-requests/",
        AdminRoleRequestListView.as_view(),
        name="admin-role-request-list",
    ),
    path(
        "admin/role-requests/<int:pk>/",
        AdminRoleRequestDetailView.as_view(),
        name="admin-role-request-detail",
    ),
    path(
        "admin/role-requests/<int:pk>/review/",
        AdminRoleRequestReviewView.as_view(),
        name="admin-role-request-review",
    ),
    path(
        "roles/<str:role_name>/",
        UserRoleRemoveView.as_view(),
        name="remove-role",
    ),
    path(
        "password/reset/",
        PasswordResetRequestView.as_view(),
        name="password-reset-request",
    ),
    path(
        "password/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]
